schemaVersion: 2.2.0
metadata:
  name: coolstore-monolith-legacy
attributes:
  che-theia.eclipse.org/sidecar-policy: mergeImage
  controller.devfile.io/storage-type: ephemeral
components:
  - name: dev-tools
    attributes:
      container-overrides: {"securityContext": {"privileged": true}}
    container: 
      image: registry.redhat.io/devspaces/udi-rhel8:3.12
      memoryLimit: 6Gi
      mountSources: true
commands: []